all:
  children:
    k8s_cluster:
      children:
        k8s_master:
          hosts:
            master:
              ansible_host: 3.64.147.108
        k8s_workers:
          hosts:
            worker1:
              ansible_host: 3.70.206.66
            worker2:
              ansible_host: 18.192.121.198
    sonarqube:
      hosts:
        sonarqube:
          ansible_host: 3.66.27.222
    nexus:
      hosts:
        nexus:
          ansible_host: 3.70.234.56
    jenkins:
      hosts:
        jenkins:
          ansible_host: 3.70.53.91
    monitoring:
      hosts:
        monitoring:
          ansible_host: 3.70.253.245
