all:
  children:
    k8s_cluster:
      children:
        k8s_master:
          hosts:
            master:
              ansible_host: 18.184.134.145
        k8s_workers:
          hosts:
            worker1:
              ansible_host: 3.69.30.180
            worker2:
              ansible_host: 3.127.135.128
    sonarqube:
      hosts:
        sonarqube:
          ansible_host: 18.196.231.211
    nexus:
      hosts:
        nexus:
          ansible_host: 35.159.165.36
    jenkins:
      hosts:
        jenkins:
          ansible_host: 3.69.30.69
    monitoring:
      hosts:
        monitoring:
          ansible_host: 18.153.97.170
